### ISSUE TITLE
bug: file should be filePath

### ISSUE THREAD

**Issue by gonzoramos** [tehpsalmist/parcel-plugin-copy-files#1]
https://github.com/tehpsalmist/parcel-plugin-copy-files/blob/68e28d6e8adbdf17bc38c887154cdb732ebb3fe2/index.js#L15

**Comment by gonzoramos** [comment]
There is a small bug in the code: the first parameter should be ```filePath```, not ```file```.

**Comment by tehpsalmist** [comment]
Well darn it! Fixing that right now.

**Comment by tehpsalmist** [comment]
v0.0.4 is out and contains this fix.

**Comment by gonzoramos** [comment]
awesome - thank you so much for this plugin!! :)
